### ISSUE TITLE
a help request template

### ISSUE THREAD

**Issue by samohtGTO** [nameouschangey/Stormworks_VSCodeExtension#103]
**What I can't do right now, that I would like to**
to make a help request(issue) for help if you think you did something wrong in your code

**Why do I want to do this thing**
it would be easier if some one need help with something related to this exstension and sort it out from error in exstension

**What I think the solution would be, and how it should work**
just a template like this that you can file

**Why I can't use an existing/alternate solution**
i think it sort things better out

**Comment by nameouschangey** [comment]
https://github.com/nameouschangey/Stormworks_VSCodeExtension/discussions/categories/q-a

Enabled discussions section, I can't guarantee you'll get things resolved there - as there isn't exactly much of a community around this, and I'm not committing particularly much time to solving other people's code issues (unless they're specific to something being badly documented). But you're welcome to ask questions there, and somebody _might_ answer it.
