### ISSUE TITLE
...\.vscode\extensions\actboy168.lua-debug-1.60.0-win32-x64\runtime\win32-ia32\lua53\lua.exe: (debugger.lua):129: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by Jumper-44** [nameouschangey/Stormworks_VSCodeExtension#105]
Error when trying to simulate (F6) or building project (F7), F5 is fine.
The error happens in a microcontroller project, doesn't matter if old or new unedited "Stormworks: New Microcontroller Project".
```
...\.vscode\extensions\actboy168.lua-debug-1.60.0-win32-x64\runtime\win32-ia32\lua53\lua.exe: (debugger.lua):129: %1 is not a valid Win32 application.

stack traceback:
        [C]: in function 'assert'
        (debugger.lua):129: in upvalue 'initDebugger'
        (debugger.lua):154: in method 'start'
        ...s/actboy168.lua-debug-1.60.0-win32-x64/script/launch.lua:29: in upvalue 'f'
        (debugger.lua):205: in global 'DBG'
        (command line):1: in main chunk
        [C]: in ?
```

Getting error from the **Lua Debug** extension by actboy168 in extension version **v1.60.0**, which came out ~4 days ago when writing.

Temporary fix is reverting to an earlier version like **v1.59.0**.

**Comment by KRIShark** [comment]
I have the same issue:

`tack traceback:
        [C]: in function 'assert'
        (debugger.lua):129: in upvalue 'initDebugger'
        (debugger.lua):154: in method 'start'
        ...s/actboy168.lua-debug-1.60.0-win32-x64/script/launch.lua:29: in upvalue 'f'
        (debugger.lua):205: in global 'DBG'
        (command line):1: in main chunk
        [C]: in ?`

Have you get it work since 10 d?

**Comment by nameouschangey** [comment]
Thanks for reporting this, both, I may have some time to look into it this weekend - until then, please just bear in mind this is a side-project I maintain for fun.

It's likely just that the Lua Debug addon has updated and needs it's launch arguments changed. If you look into it and fix it ahead of me, please just Pull Request the change into this repo. Thanks.

**Comment by Jumper-44** [comment]
As of version **v1.60.1** of extension **Lua Debug** by actboy168, I no longer have this issue and works as expected.
