### ISSUE TITLE
Unable to start debugger (F6); Something is wrong with the vs code extension

### ISSUE THREAD

**Issue by KRIShark** [nameouschangey/Stormworks_VSCodeExtension#106]
**What I expected to happen**
I Expect to Start debugger

**What happened instead**
I got the error:
```
  `.vscode\extensions\actboy168.lua-debug-1.60.0-win32-x64\runtime\win32-ia32\lua53\lua.exe: (debugger.lua):129: %1 is not a valid Win32 application.
  
  stack traceback:
          [C]: in function 'assert'
          (debugger.lua):129: in upvalue 'initDebugger'
          (debugger.lua):154: in method 'start'
          ...s/actboy168.lua-debug-1.60.0-win32-x64/script/launch.lua:29: in upvalue 'f'
          (debugger.lua):205: in global 'DBG'
          (command line):1: in main chunk
          [C]: in ?`
```

I runed the 
lua.exe file and it works. 

**How do I reproduce this?**
Reliable steps that should produce this issue:
1. Install the extension
2. create project folder
3. Push F6

**Screenshots and Project zip file**
[StromWroksDepthMeter.zip](https://github.com/nameouschangey/Stormworks_VSCodeExtension/files/9768749/StromWroksDepthMeter.zip)

**Additional info**
I useing Windows 64x

Not acculy know but why dose it try to use 32 bit lua insted of 64 bit. Could it be the issue?

**Comment by KRIShark** [comment]
I tryed to set it to use the x64 lua 

Start Command:
```
cd 'c:\Users\KRIShark\Desktop\Stormworks\DepthMeter'; & 'c:/Users/KRIShark/.vscode/extensions/actboy168.lua-debug-1.60.0-win32-x64/runtime/win32-x64/lua54/lua.exe' '-e' 'dofile[[c:/Users/KRIShark/.vscode/extensions/actboy168.lua-debug-1.60.0-win32-x64/script/launch.lua]];DBG[[33032-ansi]]' 'c:\Users\KRIShark\Desktop\Stormworks\DepthMeter\MyMicrocontroller.lua'
```
Error:
```
Exception has occurred: attempt to index a nil value (global 'simulator')
stack traceback:
	MyMicrocontroller.lua:16: in main chunk
	[C]: in ?
```

ON: MyMicrocontroller.lua default on line 16 "simulator:setScreen(1, "3x3")"

**Comment by Jumper-44** [comment]
A new version: **v1.60.1** of extension **Lua Debug** by actboy168 just came out, which resolved the issue for me, and works as expected now.

So it's only version **v1.60.0** which is faulty.

**Comment by nameouschangey** [comment]
Excellent, thanks for updating on this! Glad actboy resolved it on their side.

**Comment by Spoggerific** [comment]
I had the same issue as the original poster on v1.60.0 of Lua Debug. Updating to v1.60.1 has given me a similar issue, with a different error.

`.vscode\extensions\actboy168.lua-debug-1.60.1-win32-x64\runtime\win32-ia32\lua53\lua.exe: interrupted!
stack traceback:
        [C]: in ?
        [C]: in function 'error'
        .../Common/LifeBoatAPI\Tools\Simulator\SimulatorSandbox.lua:62: in global 'require'
        ...xamples_and_tutorials/examples/simple_styled_buttons.lua:12: in field '?'
        .../Common/LifeBoatAPI\Tools\Simulator\SimulatorSandbox.lua:67: in field 'require'
        ...ormworks\Controllers\screentesting\_build\_simulator.lua:28: in main chunk
        [C]: in ?`

When I try to run the debugger with F6, the debug window with screen contents will pop up, but things seem to stop there - it won't render the screen or change to the size I have set in the simulator options.

Compiling with F7 doesn't work either, giving the following error:

`.vscode\extensions\actboy168.lua-debug-1.60.1-win32-x64\runtime\win32-ia32\lua53\lua.exe: interrupted!
stack traceback:
        [C]: in ?
        [C]: in ?
        [C]: in function 'require'
        ...works/Controllers/screentesting/_build\_buildactions.lua:8: in main chunk
        [C]: in function 'require'
        ...s\Stormworks\Controllers\screentesting\_build\_build.lua:2: in main chunk
        [C]: in ?`

Things were working for me yesterday, but I imagine VSCode has updated something somewhere and broken things. I'm not sure how to find out what, if anything, has changed, or else I would post it here and try reverting.

I've tried reverting to version 1.59.0 of Lua Debug as well, which gives me the same errors as above. Only version 1.60.0 gives me the same error as the original poster.

**Comment by nameouschangey** [comment]
Closing this as it seems the new version of Actboy's debug extension is working nicely, so all good.

Spoggerific - I've replied to you on discord regarding the issue you had as it's separate/not an extension issue as far as I can see. I'm going to close this ticket though.
