### ISSUE TITLE
Undefined global 'screen'

### ISSUE THREAD

**Issue by MLDKYT** [nameouschangey/Stormworks_VSCodeExtension#107]
**What I expected to happen**
'Screen' not being underlined and getting autocompletion

**What happened instead**
'Screen' underlined and no autocompletion

**How do I reproduce this?**
Reliable steps that should produce this issue:
1. Create a new project.
2. Open the default MyMicrocontroller.lua file.
3. See that 'Screen' is underlined yellow and there is no autocompletion when typing.

**Screenshots and Project zip file**
![image](https://user-images.githubusercontent.com/59791284/204323006-d8beef1c-24c4-4d42-b776-eb958fbcc1e5.png)
[Untitled.zip](https://github.com/nameouschangey/Stormworks_VSCodeExtension/files/10105373/Untitled.zip)

**Additional info**
None

**Comment by MLDKYT** [comment]
![image](https://user-images.githubusercontent.com/59791284/204325458-4f495df8-e457-4a54-8dfb-87e2f5c86a18.png)

**Comment by MLDKYT** [comment]
Also the async does not autocomplete correctly.

**Comment by nameouschangey** [comment]
Fixed in upcoming update, thanks very much
