### ISSUE TITLE
Can't run boilerplate, simulator is nil

### ISSUE THREAD

**Issue by TheLogan** [nameouschangey/Stormworks_VSCodeExtension#108]
**What I expected to happen**
I expected the boilerplate file to run

**What happened instead**
It crashed with the following error
`stack traceback:
        h:\Coding\Stormworks\Circuit101\MyMicrocontroller.lua:16: in main chunk
        [C]: in ?`
On line 15 it runs the following
`simulator = simulator`
I am very new to LUA but I work as a developer and to me, that looks wrong, you are to my understanding, trying to assign a variable to itself. However, when I try to run (using F5) the editor tells me that the simulator is `nil`, and crashes.

**How do I reproduce this?**
Reliable steps that should produce this issue:
1. create new project following the extension guide
2. run the MyMicrocontroller.lua file
3. ????
4. Profit!

**Screenshots and Project zip file**
If visual, please provide screenshots of the issue.
Please also upload your project folder as a .zip file
[stormworks test.zip](https://github.com/nameouschangey/Stormworks_VSCodeExtension/files/10125156/stormworks.test.zip)

**Additional info**
Any additional information that will aid this bug getting fixed

**Comment by TheLogan** [comment]
I just checked with and neither simulator nor __simulator exists (I've created multiple projects just to be sure), my suspicion is that a file defining simulator is missing in the library.
The only two files that reference the keyword is the MyMicrocontroller and settings.json

**Comment by nameouschangey** [comment]
I've had a check, it doesn't reproduce for me.
Can you try running the simulator using the command (CTRL+SHIFT+P) "Stormworks: Simulate Microcontroller"

My gut feeling is you might have something else intercepting F6 and having it run the file as a regular lua file.
You should be getting a build/_simulator.lua file generated if it's actually running through the extension

**Comment by TheLogan** [comment]
Doh I think I understand now.
So F5 runs using just standard LUA where the simulator doesn't exist and F6 runs via the lifeboat framework where the simulator does exist, right?
Cause with F6 it works and with F5 it fails because simulator is nil

**Comment by nameouschangey** [comment]
Yeh exactly, F5 just runs whatever's setup in your launch.json/current debugger - which will normally be an action "Run Lua", so no additional Stormworks stuff.

F6 for the simulator, F7 for the build process
And they both have command names (CTRL+SHIFT+P => "Stormworks") in case you want to rebind them, etc.
