### ISSUE TITLE
Class usage failure: global c is nil

### ISSUE THREAD

**Issue by yeskiy** [nameouschangey/Stormworks_VSCodeExtension#111]
**What I expected to happen**
Can compile class and work properly

**What happened instead**
Compiled without `#self` operator instead

**How do I reproduce this?**
try to compile that
```lua
local Array = {__type = "utility.array", default_size = 10}

function Array:make(v, to)
    local array = {}
    for i = 1, to do array[i] = v end
    return array
end

function Array:map(fn)
    if type(fn) == "string" then
        local path = fn
        fn = function(v, i, arr) return v[path] end
    end

    local out = Array(#self)
    for i, v in ipairs(self) do out[i] = fn(v, i, self) end

    return out
end
```

**Screenshots and Project zip file**
![image](https://user-images.githubusercontent.com/39830788/216788938-4a086ca9-e207-4de9-b45b-368ae1105bef.png)

**Additional info**
It looks like minimizer ignore some class/object functionality. Should mark that as high-priority

**Comment by yeskiy** [comment]
*Workaround:*
change `c` (or any symbol that replace `self`) to `self`

**Comment by nameouschangey** [comment]
closing this, as there's unfortunately not a great option either way
either, self is protected, in which case - implicit self works fine, but explicit self param becomes extreme bloat
or, self is left unprotected, in which case implific self doesn't work - but can be written as:

In this case, I'm going with the latter as a lot of code that relies on self minimizing will break by this change, and I don't currently have the time to refactor that stuff. Not ideal, but just a reality of it I'm afraid.

`
local Array = {
__type = "utility.array",
default_size = 10,

make = function(self, v, to)
    ....
end,

map = function(self, fn)
end
}
`
