### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by WeponizedAutism** [nameouschangey/Stormworks_VSCodeExtension#135]
**What I expected to happen**
My code to build/simulate.

**What happened instead**
I receive a runtime error that says: No runtime is found, you need to compile it yourself.

**How do I reproduce this?**
Reliable steps that should produce this issue:
Not Sure

**Screenshots and Project zip file**
![luaerror](https://github.com/user-attachments/assets/7f43b46d-9501-4512-80d9-1f48a3a65da4)

[Script1-20240830T225554Z-001.zip](https://github.com/user-attachments/files/16822602/Script1-20240830T225554Z-001.zip)

**Additional info**
All dependencies show as installed.

**Comment by OSCH04** [comment]
I have the same Issue, how did you fix it ?

**Comment by WeponizedAutism** [comment]
Hey! This was a while ago so I might be remembering incorrectly, I believe what I did was I reverted either my lua version or my lua debug version in VS Code. Sorry I can't be more help!

Best of Luck!

**Comment by mchl12** [comment]
I was able to solve the same issue just now by reverting the 'Lua Debug' extension to version '1.60.4'

**Comment by OSCH04** [comment]
I search on the Stormworks discord and found this solution 

https://discord.com/channels/357480372084408322/578586360336875520/1227013818933055650

"In the runtime folder of the above package I added additional directory named 5.3 in the runtime directory. The directory has a copy of the contents of the Lua53 directory in the same dir.
So make a copy of Lua53 and rename it to 5.3"

https://media.discordapp.net/attachments/578586360336875520/1227013990970953829/image.png?ex=679017d4&is=678ec654&hm=d9859f8f93f2db2fd1bc4b53372fd0037810197f8ef43a9d3af50b2da35d90f9&=&format=webp&quality=lossless
