### ISSUE TITLE
Running Simulate or Build does 'nothing'

### ISSUE THREAD

**Issue by gregwinn** [nameouschangey/Stormworks_VSCodeExtension#137]
**What I expected to happen**
Started a fresh project, did not make any changes to the example code provided. Tried to use F6 (Simulate) it switches over to debug menu in VS code, i expected it to launch showing me a circle.

**What happened instead**
It does not run nor does it provide any output in the debug menu. So I have no idea how to debug or fix this.

**How do I reproduce this?**
Reliable steps that should produce this issue:
1. New Project
2. F6 to simulate the unchanged lua file

**NOTE**
Running VSCode on Linux (Fedora 41)

**Comment by gregwinn** [comment]
I will also try this on a windows box, will report back. Really want this extension to work!!

**Comment by gregwinn** [comment]
Running on windows I get the following issue when trying to simulate:

```
Exception has occurred: attempt to index a nil value (global 'simulator')
stack traceback:
	MyMicrocontroller.lua:16: in main chunk
	[C]: in ?
```

I see issue: https://github.com/nameouschangey/Stormworks_VSCodeExtension/issues/108 

Running Simulate from the command bar I get the following issue:
![Screenshot 2024-11-27 150316](https://github.com/user-attachments/assets/571d10a7-c8a3-4adb-b20c-bec49b6a4b9c)

**Comment by gregwinn** [comment]
Ok found the solution on Windows!!!! I have not tried on Linux yet. 

You need to install Lua Debug extension 1.61.0 right now its at 2.x... I installed version Lua Debug 1.61.0 and unchecked the "Auto Update". Then ran simulate and it worked! I will close this and provide an update for Linux later.

**Comment by gregwinn** [comment]
Still not working on Linux even when using the older Lua Debug version. I get this error:

![Screenshot From 2024-11-27 19-47-14](https://github.com/user-attachments/assets/d6363418-c783-4f61-9502-116605aedb3f)

**Comment by scottbottgo** [comment]
I would benefit from this being solved on Linux, any ideas?

**Comment by scottbottgo** [comment]
1.42.1 yields interesting results for me, completely different error.

**Comment by scottbottgo** [comment]
1.43.0, I need a valid ELF header for the socket.core file :/
