### ISSUE TITLE
Restarting Debugger + Zoom/Centering

### ISSUE THREAD

**Issue by Dealman** [nameouschangey/STORMWORKS_VSCodeExtension#20]
Been using this a bit more now for video editing, so I've got some more feedback for you 😉 

### Restart
When you start a debug session, you can choose to pause, restart or stop the session. Pausing is obvious, it pauses and shows the current instruction, restart _(at least for me)_ doesn't do anything and stopping stops the session as expected.

Is restart meant to work? It would be a better workflow to make changes, hit restart or its shortcut to refresh the simulator session instead of stopping and starting a new one several times.

### Zoom/Centering
It'd be nice if it either remembered the last transform or tries to zoom and center the display automatically upon start as I always find myself having to move and/or zoom out.

**Comment by nameouschangey** [comment]
For the restart, I'm not sure how fixable it'll be.
I'll definitely have a look though. Generally I just kill the session and start a new one - out of an old habit. But I'll see what can be done.

(Just on the extreme off-chance you don't already know - you can also set breakpoints by clicking to the left of the line number, and it'll pause when it hits that line. I imagine you've already seen that though)

For Zoom/Centering, that's a good idea.
I'll see what I can do!

Thanks for these!

**Comment by nameouschangey** [comment]
Added this :)
Will be in the next patch.
I've unfortunately got ill, and so it might be the first week of 2022 I push it.
