### ISSUE TITLE
Wrong charset

### ISSUE THREAD

**Issue by SengirVampire** [nameouschangey/STORMWORKS_VSCodeExtension#24]
Some Characters aren't aligned correctly and some characters are missing in your simulator.
My controllers often use a mechanic to write proportional but the misalignment of the characters makes it very problematic to use the code written in VStudio in my controllers.
I don't know how you implemented the font but perhaps this is fixable.

**Comment by nameouschangey** [comment]
Thanks very much for raising this.

The font is hand made, so there's a chance of errors in some characters.

Could you let me know which ones are missing, or incorrect (a screenshot of the game will also save some time) - and I'll get them implemented.

Thanks very much!

**Comment by nameouschangey** [comment]
Sorry, can you also upload one of your MCs for me, so I have a test case to try to get it working right.

Thanks

**Comment by SengirVampire** [comment]
Hello,
that’s a really fast response from you 😊

I attached an image, showing all chars from stormworks and from lifeboat. Some chars, like () [] “ . aren’t aligned correctly, $ & and | are missing, # and 0 are mirrored, …
I hope this will help.

And here is my drawText function to test things out.
require("_build._simulator_config")

charSize={3,3,1,0,0,0,0,3,2,2,0,1,1,1,3,1,0,2,0,0,0,0,0,0,0,0,3,3,1,1,1,1,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,2,1,2,1,0,2,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,1,3,1,0}

function onTick()
end

function onDraw()
    drawText(0,0,"HELLO WORLD!")
    drawText(0,6,"(213.2115)")
end

function drawText(x,y,text)
    for i=1,#text do
        c=text:sub(i,i)
        l=charSize[string.byte(c)-31]
        screen.drawText(x-math.floor(l/2),y,c)
        x=x+5-l
    end
end

Thanks for this great Visual Studio extension.

Best regards and happy holidays,

Thorsten

Von: Gordon Mckendrick ***@***.***>
Gesendet: Sonntag, 19. Dezember 2021 11:54
An: nameouschangey/STORMWORKS_VSCodeExtension ***@***.***>
Cc: SengirVampire ***@***.***>; Author ***@***.***>
Betreff: Re: [nameouschangey/STORMWORKS_VSCodeExtension] Wrong charset (Issue #24)


Thanks very much for raising this.

The font is hand made, so there's a chance of errors in some characters.

Could you let me know which ones are missing, or incorrect (a screenshot of the game will also save some time) - and I'll get them implemented.

Thanks very much!

—
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnameouschangey%2FSTORMWORKS_VSCodeExtension%2Fissues%2F24%23issuecomment-997370433&data=04%7C01%7C%7C9a678d53ffd145ea54f808d9c2ddd912%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637755080356727591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=c%2FD5lWeI3K%2BL%2BrAzDDkRxZeW0wLPaOZTGj2Iy1eg7Ms%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANS3G7FPKGCIZUQ6UMMSPDTURW2UDANCNFSM5KLXYC5A&data=04%7C01%7C%7C9a678d53ffd145ea54f808d9c2ddd912%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637755080356727591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Dywn4NjZnB8uxIOM95tsJ6TMGfo7xXW8IHgtFkqKo%2FY%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C9a678d53ffd145ea54f808d9c2ddd912%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637755080356727591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=x6uHidrjYhWxt2Ut7iwuvymSKv56I98HiMuX1ld0B9M%3D&reserved=0> or Android<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C9a678d53ffd145ea54f808d9c2ddd912%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637755080356727591%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iEHlI%2FqZLrM32R6QkPtMKyiR10Xkkv6Bo2VHyw4Cx58%3D&reserved=0>.

**Comment by nameouschangey** [comment]
Perfect, thanks very much!
I csnt actually see the image, github seems not to have used the attachments (I imagine you might need to upload on the tracker directly).

Bu mo worries, you've given me enough to work through this.

Thanks again!

**Comment by SengirVampire** [comment]
![Stormworks Charset](https://user-images.githubusercontent.com/56996732/146674370-932641b5-44f2-4684-a269-c1996d9fdb5b.jpg)

**Comment by nameouschangey** [comment]
Legend, thanks so much!

**Comment by nameouschangey** [comment]
Fixed - patch releasing later today
