### ISSUE TITLE
Keyword "goto" gets minified => Lua Error

### ISSUE THREAD

**Issue by THE-SIMPLE-MARK** [nameouschangey/STORMWORKS_VSCodeExtension#28]
The keyword `goto` used in Lua gets minified (it doesn't even get defined in my testing) and as a result Lua will throw an Error.

I have not looked into your work yet, but hopefully this will be an easy fix!

Little feedback on Lifeboat API: I absolutely love it! I've made a Batch executable to copy the release `script.lua` file to the mission folder, if you could automate that so it copies the release after pressing F7 to a folder then that would be awesome!

**Comment by nameouschangey** [comment]
Ah, thanks for raising this.
It should be extremely easy to fix, so will get that in shortly.

Will dohble check all other 5.3 keywords while I'm at it.
Thanks!

**Comment by nameouschangey** [comment]
For the second point, just run your script.lua copy thing from the _build/_post_build_actions.lua script.

Its there for exactly that!

**Comment by THE-SIMPLE-MARK** [comment]
Ah, thanks! That response time is best I've seen on a Github issue for some time, nice job! 👏

**Comment by nameouschangey** [comment]
That's it fixed, will be in the next patch (0.0.8)
Will be aiming to test and deploy in the next week

Thanks again for raising it.
