### ISSUE TITLE
1x3 monitor option missing

### ISSUE THREAD

**Issue by lsedberg** [nameouschangey/STORMWORKS_VSCodeExtension#50]
All screen sizes are available in the F6 (Microcontroller simulator), *except* for the **Monitor 1x3**.

![image](https://user-images.githubusercontent.com/80771288/149643716-cf0a91ad-adae-40d1-a8b3-244d3fa52bcf.png)

**Comment by nameouschangey** [comment]
Thanks, no idea how I didn't see this.
Might have gone from an outdated wiki article when I was getting the monitor sizes (or just selective blindness)

Anyway, will get this in.
Thanks!

**Comment by nameouschangey** [comment]
That's it added now - thanks again for pointing it out!
It'll be available in the next patch 0.0.11 - which might be a few days/next weekend, as I've made pretty sweeping changes (to accurately represent some "odd" behaviours that exist in gmae) - and I'd like to test it more than I have so far.
