### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by PirateJake2000** [nameouschangey/STORMWORKS_VSCodeExtension#58]
When trying to build (F7) I'm prompted with this message:
![image](https://user-images.githubusercontent.com/79664479/150611137-f9367165-f9d7-474e-aff3-6f976b4a660f.png)
I have not done anything stupid, I think the most I did was rename "MyMicrocontroller" to "main" that's when it stopped working however when renaming back to MyMicrocontroller it continued to give me that error 

I'll be looking at this daily but if you want more details I would much rather use discord my tag: PirateJake2000#5585

**Comment by nameouschangey** [comment]
Thanks for raising this, I'm afraid you'll have to wait for the next patch - I've got a fix sitting for it.
Sorry for the frustration until then.


As a "quick fix" for the next couple of days:
if you delete that predictedBoilerplateSize from tostring(sizeWithoutBoilerplate + predictedBoilerplateSize) you'll be able to keep working till the patch comes out. (or implement the actual fix itself, there's a missing or 0 from where predictedBoilerplateSize gets assigned)

Thanks again for reporting it, and apologies for the frustration I'm sure it's causing!

**Comment by nameouschangey** [comment]
(just fwiw, the reason you're seeing it now is you're minimizing a file that's going into the "close to 4000 minified characters" size. You've not done anything wrong, it's entirely a bug)

**Comment by PirateJake2000** [comment]
ok epic, removed that code you sent and it worked fine. loving this so far
