### ISSUE TITLE
Hexadecimals

### ISSUE THREAD

**Issue by LyamBRS** [nameouschangey/STORMWORKS_VSCodeExtension#60]
I noticed that the game does not support the use of hexadecimals even though Lua natively does.
That lead me to debug for several hours a code that was working perfectly fine in the editor, but once pasted to Stormworks crashed my script.

Saying I was pissed is an understatement. After all Lua natively supports hexadecimals so I wouldn't think that Stormwork wouldn't.

I was simply wondering if it would be possible to do the same in this code extension. Although it's a nice feature to have, the game straight up does not support them.

I'm a bit used to use hexadecimals all the time as I normally code hardware like microcontrollers in Assembly or C and hexadecimals is useful in those cases and as I was coding some 8 bit conversions I thought I'd use them but as stated above, Stormworks does not support them.

Anyway, I'd be glad to hear your thoughts about this and if it's worth doing or not.
Thanks in advance!

- Lyam

**Comment by nameouschangey** [comment]
Sorry, I'm not sure I'm understanding what you're asking for here.

If it's specifying numbers as hex, then that works fine in game and in the Extension:
`
onTick = function()
    output.setNumber(1, 0x00101)
end
`
will output 257 as expected.

I'm guessing you're asking for something different though?

Can you give me:
 - a code snippet showing what you want to be able to do that doesn't currently work
 - what you expect/want to happen
 - what currently happens instead.
 
Many Thanks

**Comment by LyamBRS** [comment]
![image](https://user-images.githubusercontent.com/98483741/151271075-a6ae49a4-9045-438a-ae15-7a00d6cbe71f.png)
this is in game, the game thinks xff is a variable and gives me an error.
"cannot do arithmetic's on nil variable "xff"

if it works for you then there's clearly something im missing.

In the extension is works just fine obviously.

**Comment by nameouschangey** [comment]
Ah, gotcha. Thanks!

What I tested was lacking, 0x00101 is all digits and I'm guessing that's where the game goes wrong.

Will recheck it tomorrow, but assuming it reproduces (don't see why it wouldn't) - a decent solution might be to add it into the build process. Turn all hex into decimals as a build step.

**Comment by nameouschangey** [comment]
Implemented in upcoming patch
Converts all hexadecimals into raw numbers so that they work in-game now.
