### ISSUE TITLE
Simulator: Colours wrap at 256

### ISSUE THREAD

**Issue by nameouschangey** [nameouschangey/STORMWORKS_VSCodeExtension#61]
Colors wrap at 256, not min/max

**Comment by nameouschangey** [comment]
PS: Color also is floored to ints

**Comment by RCTrapdoor** [comment]
Pretty sure the game does this too. It's a bit annoying but that's the convention they chose. The simulator correctly mimics the behavior in the game.

**Comment by nameouschangey** [comment]
Oh, is it?
This is the behaviour in the sim:
- colours DONT wrap (but I thought they should?) - they're min/maxed at 0-255
- colours are *maybe* floored to ints (but they definitely should be)

I think I gave it a title that wasn't helpful :D

**Comment by RCTrapdoor** [comment]
Aah yeah we're totally in agreement then. :D

**Comment by nameouschangey** [comment]
Fixed in upcoming patch
