### ISSUE TITLE
mapToScreen and screenToMap raises exception: Cannot use screen functions outside of onDraw.

### ISSUE THREAD

**Issue by RCTrapdoor** [nameouschangey/STORMWORKS_VSCodeExtension#64]
Simulator_ScreenAPI.lua raises exception on using map.mapToScreen / screenToMap in onTick. Lines 402 and 429 "screen._ensureIsRendering()" both cause the script to stop prematurely with exception raised on line 43 "screen._ensureIsRendering()".

**Comment by nameouschangey** [comment]
Fixed in upcoming patch.
