### ISSUE TITLE
Build: Add ability to only minimize certain sections of the code (Feature Request)

### ISSUE THREAD

**Issue by Toast732** [nameouschangey/STORMWORKS_VSCodeExtension#69]
**Description**
The ability to only minimize certain chunks of the code, for example, lets say if I had a really long script, and errors came up time to time, I would like to minimize it, however then trying to debug it would be a nightmare, so what would be nice is then to only be able minimize lets say just the onCustomCommand function, that way you can still easily debug the code, while still having it minimized as to not go over the character limit.

**Comment by nameouschangey** [comment]
On experimental branch currently, but added extensive new code-tag feature

Can now tag the sections you don't want minified, and they won't be touched.
