### ISSUE TITLE
Fatal error:  Socket is not connected

### ISSUE THREAD

**Issue by SentyFunBall** [nameouschangey/STORMWORKS_VSCodeExtension#70]
Usually, when first installing the extension, and simulating a fresh project, it will give the error `Exception has occurred: Socket is not connected`. No clue why or how to fix it. I somehow got around the error when I first installed, but I don't remember how. It prevents the entire extension from working at all.

**Comment by SentyFunBall** [comment]
Full error 
`Exception has occurred: Socket is not connected
stack traceback:
    ...ools/LifeBoatAPI/Tools/Simulator/SimulatorConnection.lua💯 in method 'sendBytes'
    ...ools/LifeBoatAPI/Tools/Simulator/SimulatorConnection.lua:50: in method 'sendCommand'
    ...eBoatAPI/Tools/LifeBoatAPI/Tools/Simulator/Simulator.lua:223: in function 'simulator.setScreen'
    ...PI/Tools/LifeBoatAPI/Tools/Simulator/SimulatorConfig.lua:32: in method 'configureScreen'
    ...eBoatAPI/Tools/LifeBoatAPI/Tools/Simulator/Simulator.lua:274: in function 'simulator._beginSimulation'
    _build/_simulator.lua:12: in main chunk
    [C]: in ?`

**Comment by nameouschangey** [comment]
note, implement following change

        if not attachToExistingProcess then
            local simulatorExePath = LifeBoatAPI.Tools.Filepath:new(simulatorFile)
            this._simulatorProcess = io.popen("\"" .. simulatorExePath:win() .. " -logfile \"" .. simulatorLogFile .. "\"\"", "w")
        end

**Comment by SentyFunBall** [comment]
From what I'm testing in C#, you can start processes with spaces in the file name. I used the following code, and it worked well for both my actual user file (no spaces), and the temp one I created for testing, which has a space. Both open the simulator:
`string test = "Senty Funball";
                string thing = "C:/users/" + test + "/.vscode/extensions/nameouschangey.lifeboatapi-0.0.12/assets/simulator/STORMWORKS_Simulator.exe";
                Process.Start(thing);`
Not sure what this means, or how to convert it to Lua if that's what you're using to start the simulator.

**Comment by nameouschangey** [comment]
Process.Start is significantly more pleasant to work with than lua's popen
If you want to test a solution to this, you need to do so in the relevant environment (lua)

**Comment by SentyFunBall** [comment]
Right, I'll start working on translating that into lua.

**Comment by nameouschangey** [comment]
Potentially fixed in upcoming patch, will reopen with Digger if they report the issue persists

**Comment by ashJA65** [comment]
Hello - I'm getting a similar issue after installing this extension for the first time. I'm not sure if the fact that my C:\Users\Adam Ash
has a space in Adam Ash

Full error, which occurs when running the first 01_GettingStarted.lua file (or any other):
`Exception has occurred: Socket is not connected
stack traceback:
	...ools/LifeBoatAPI/Tools/Simulator/SimulatorConnection.lua:100: in method 'sendBytes'
	...ools/LifeBoatAPI/Tools/Simulator/SimulatorConnection.lua:50: in method 'sendCommand'
	...eBoatAPI/Tools/LifeBoatAPI/Tools/Simulator/Simulator.lua:223: in function '__simulator.setScreen'
	...PI/Tools/LifeBoatAPI/Tools/Simulator/SimulatorConfig.lua:32: in method 'configureScreen'
	...eBoatAPI/Tools/LifeBoatAPI/Tools/Simulator/Simulator.lua:274: in function '__simulator._beginSimulation'
	_build/_simulator.lua:12: in main chunk
	[C]: in ?`

Also, the terminal output (note that it seems to trip up on the space in Adam Ash:
`PS C:\Stormworks MCproject\Running1>  & 'c:/Users/Adam Ash/.vscode/extensions/actboy168.lua-debug-1.58.1-win32-x64/runtime/win32-ia32/lua53/lua.exe' '-e' 'dofile[[c:/Users/Adam Ash/.vscode/extensions/actboy168.lua-debug-1.58.1-win32-x64/script/launch.lua]];DBG[[2852,ansi]]' 'c:\Stormworks MCproject\Running1\_build\_simulator.lua' 'c:/Users/Adam Ash/.vscode/extensions/nameouschangey.lifeboatapi-0.0.15//assets/simulator/STORMWORKS_Simulator.exe' 'c:/Stormworks MCproject/Running1//_build/_debug_simulator_log.txt'
'c:\Users\Adam' is not recognized as an internal or external command,
operable program or batch file.`

Sorry if I'm missing something here - I'm new to using VSCode extensions like this

**Comment by SentyFunBall** [comment]
100% it seems to be caused by spaces in the username. Nameous should be working on a fix soon.

**Comment by nameouschangey** [comment]
The good news, is I've got a setup to reproduce it now.
Removed that "Fixed" tag as it clearly isn't.

Working on it! Sorry for the frustration

**Comment by nameouschangey** [comment]
Fixed in latest 0.0.16
Just re-open this if I'm wrong and I'll look at it again. It appears to be good now though.
