### ISSUE TITLE
Addon API Documentation: setVehicleTank amount value incorrect.

### ISSUE THREAD

**Issue by Shillelagh1** [nameouschangey/STORMWORKS_VSCodeExtension#71]
![image](https://user-images.githubusercontent.com/96487743/154884060-14a25eae-0db7-4192-b755-9a30290177a0.png)

The documentation refers to the "amount value" as a tenth of the value that will be filled but this is incorrect.
An amount value of 70 will fill the tank to 700 liters, while a value of 70 will fill a tank to 70 liters.

**Comment by Shillelagh1** [comment]
Correction (mistype), I meant to write the documentation says an amount value of 70 will fill the tank of 700 liters. Did not clarify.

**Comment by nameouschangey** [comment]
Thanks for this, I really need to update the entire addon docs/intellisense.

Just to check, so it shouldn't say "litres * 10"; just "amount in litres"
500 -> 500 ingame right?

**Comment by nameouschangey** [comment]
Fixed in upcoming patch (along with updating all existing addon api docs)
