### ISSUE TITLE
Minimizer creates 4k+ char files with boilerplate

### ISSUE THREAD

**Issue by SentyFunBall** [nameouschangey/STORMWORKS_VSCodeExtension#72]
After minimizing this fairly chunky script, it is 3,769 characters long. The extension adds the boilerplate code because it's less than 4k, and this puts the code over 4096 characters, breaking the vehicle. 

I know you can disable adding the boilerplate in the settings, but I think it would be smarter if it could know how large the file will be after adding the boilerplate, and opt-out even if the setting is enabled. Or maybe just leave out the "Developed & Minimized using LifeBoatAPI" part, leaving the author links.

**Comment by nameouschangey** [comment]
It should!
If that's not happening I've screwed it and introduced a bug somewhere.

Can you double check the "force boilerplate" option is disabled; as that overwrites the behavior/forces the boilerplate regardless of size. It's very likely a bug though.

**Comment by nameouschangey** [comment]
Not managing to reproduce this, so can you zip up your project and upload it.
Thanks.

**Comment by SentyFunBall** [comment]
[SenGraph1.1.zip](https://github.com/nameouschangey/STORMWORKS_VSCodeExtension/files/8122125/SenGraph1.1.zip)
This is the project I've been working on. It gets minimized, to 3769 characters. The extension says "Hey! It's below 4000, lets add the boilerplate!" And it does, putting the character count at 4147, above Stormworks' limit.

And yes, force boilerplate is off.
![image](https://user-images.githubusercontent.com/57205125/155266981-3ed22046-9cce-4dc8-91f0-bb4d8d9c306e.png)

**Comment by nameouschangey** [comment]
Thanks!
