### ISSUE TITLE
Issue with map.mapToScreen function compared to stormworks

### ISSUE THREAD

**Issue by theutree** [nameouschangey/STORMWORKS_VSCodeExtension#74]
map.mapToScreen returns the wrong values in the simulator compared to what it does in stormworks.
Instead of returning the desired screen coordinates for x and y it returns the same number scaled by the width and height of the screen for booth x and y

example:
```lua
ticks = 0

function onTick()
    ticks = ticks + 1

    x = 20*math.sin(ticks/100)
    y = 20*math.cos(ticks/100)

end

function onDraw()

    screen.drawMap(0,0,1)
    w = screen.getWidth()
    h = screen.getHeight()

-- green circle
    tX, tY = map.screenToMap(0, 0, 1, w, h, x+w/2, y+h/2)
    tX, tY = map.mapToScreen(0, 0, 1, w, h, tX, tY)
    screen.setColor(0, 255, 0)
    screen.drawCircleF(tX, tY, 4)

-- red circle
    screen.setColor(255,0,0)
    screen.drawCircleF(x+w/2, y+h/2, 2)
end
```
if you first run this in stormworks you will see that the green and red circle follow each other precisely, this is to be expected since they are both using the same coordinates except the green circles coordinates are converted into map coordinates using the map.screenToMap function, and then back to screen coordinates using the map.mapToScreen function. In the simulator you will see the green circle instead follows a diagonal line. It seems to convert it correctly but uses the x map coordinate for calculating the y screen coordinate

**Comment by nameouschangey** [comment]
Thanks for raising this, will see if I can find how Stormworks implements it.

**Comment by theutree** [comment]
np, after looking more closely at it. it seems it is using the x input for both the x and y output

**Comment by nameouschangey** [comment]
Ah yep, cheers for looking into it before I've had a chance to.
Fixed now, will be released in next patch.

In future, if you end up searching through the code and find something wrong - feel free to just Pull Request the change in, and then your contribution will be in the git logs, if you care about that kind of thing.

Thanks!
