### ISSUE TITLE
Suggestion: Option to build as microcontroller / addon as flag in file

### ISSUE THREAD

**Issue by o-brkyr** [nameouschangey/STORMWORKS_VSCodeExtension#77]
Currently having a hard time trying to build an addon project as it's minimizing global tables like `matrix`, and functions like `onCustomCommand`. This may be due to the folder being a 'microcontroller' project. I have tried manually overriding the extension to build as an addon project via the settings to no avail.

Having build settings not completely transparent isn't ideal in my opinion.

A potential solution (or, addition) to this would be to have `--!MICROCONTROLLER` or `--!ADDON` or something similar as a text flag. If this is present in a file, the minimizer will pass in the relevant constants, overriding folder project type. Any other file in the project will build as normal.

Maybe I'm just going about building wrong, but may be food for thought nonetheless.

**Comment by nameouschangey** [comment]
Just create a separate Addon project - you can have it in the same workspace as the Microcontroller one; so they're both visible together in VSCode at the same time.

The build process is project wide, and more importantly - code written for Microcontrollers is rarely going to be suitable for addons (and vice versa); amongst issues of intellisense.
Creating some kind of "mixed" project is a nightmare with no benefits.

Thanks for raising anyway.
