### ISSUE TITLE
LUA simulator error due to space in path

### ISSUE THREAD

**Issue by THE-SIMPLE-MARK** [nameouschangey/STORMWORKS_VSCodeExtension#79]
The LUA micro simulator errors with the following: 
![image](https://user-images.githubusercontent.com/57036815/161546493-a0e46bdf-d213-4da8-9920-e00faf6641a6.png)
(Origin of error: `C:\Users\SIMPLE MARK\.vscode\extensions\nameouschangey.lifeboatapi-0.0.13\assets\LifeBoatAPI\Tools\LifeBoatAPI\Tools\Simulator\SimulatorConnection.lua`)

This also appears in the debug console suggesting that the path doesn't account for spaces (especially in my username: "SIMPLE MARK"):
![image](https://user-images.githubusercontent.com/57036815/161547000-e2678153-8035-408b-bd26-01b93108d17c.png)

**Comment by THE-SIMPLE-MARK** [comment]
> Thanks for raising this, I thought I'd already fixed it a few patches ago.
> 
> I'll look into it again, maybe I either didn't fix it as well as I thought I had, or broke it in a subsequent patch.

Forgot to mention that I'm running Windows 11, the OIS is basically the same as windows 10 backend wise so I doubt that would be the problem, nor have I experienced any other programs on here with similar issues.

**Comment by nameouschangey** [comment]
Fixed in latest
