### ISSUE TITLE
Suggestion: Custom tick rate

### ISSUE THREAD

**Issue by SentyFunBall** [nameouschangey/Stormworks_VSCodeExtension#82]
I think it would be cool (helpful? debatable) to be able to set a custom tick rate instead of the preset options.
Short and sweet

**Comment by nameouschangey** [comment]
Thanks for the suggestion.

Could you give a use-case where having more freedom over the tick-rate/frame-skip would be genuinely beneficial (what it would let you do that you can't now)?

Thanks.

**Comment by nameouschangey** [comment]
Closing as no reply in 23 days.
