### ISSUE TITLE
Simulator locks up on unlimited tick rate

### ISSUE THREAD

**Issue by SentyFunBall** [nameouschangey/Stormworks_VSCodeExtension#83]
When I select unlimited tick rate, after a few seconds the simulator becomes unresponsive. The lua is still updating, but the window will not respond to mouse inputs, and cannot be exited.
I usually use full screen, and it may just be my script, i'll comment if i find anything else

**Comment by nameouschangey** [comment]
Thanks for raising this one,

My gut feeling would be it's that the network is queuing up commands faster than it's handling them. 
Do you have a use-case where unlimited tick-rate would be helpful? (Just so I can figure out priority)

**Comment by nameouschangey** [comment]
Closing as no response in 30+ days, and it's not clear that this would be easily solvable.
