### ISSUE TITLE
Suggestion: Allow changing inputs from the simulator window

### ISSUE THREAD

**Issue by griffi-gh** [nameouschangey/Stormworks_VSCodeExtension#84]

**Comment by nameouschangey** [comment]
Thanks for adding this, I agree - it would be a helpful feature

I'm not so sure on properties though; as those can't change at runtime ingame - so there's less situations where I can see the benefit. Feel free to say what use cases you have though

**Comment by griffi-gh** [comment]
yeah, i agree

**Comment by samohtGTO** [comment]
maybe in vs debug menu were you cen change them
