### ISSUE TITLE
Bug: Sections don't work?

### ISSUE THREAD

**Issue by griffi-gh** [nameouschangey/STORMWORKS_VSCodeExtension#87]
Primitives.lua
```
---@section TestThingy
function TestThingy()
  screen.drawClear()
  screen.drawClear()
  screen.drawClear()
  screen.drawClear()
  screen.drawClear()
end
---@endsection`
```
Primitives.lua is `require`d from the Main.lua and never used, but the code still ends up in the generated output 
```
function u()bo()bo()bo()bo()bo()end
```

**Comment by nameouschangey** [comment]
Can you upload the entire project as a zip?
I'll have a look into it

Thanks

**Comment by nameouschangey** [comment]
> by my non of the params that i know work from arg 4 to 15

You'll need to explain this comment better sorry
And if it's a separate issue, please raise it separately.

**Comment by griffi-gh** [comment]
They work fine, but the readme is wrong
You have to use
```
---@endsection
```
instead of 
```
---@endsection`
```
