### ISSUE TITLE
f7 bugs out, f6 works

### ISSUE THREAD

**Issue by Krolon0697** [nameouschangey/STORMWORKS_VSCodeExtension#89]
error at StringUtils.lua
line 52
no clue how I caused it, simulation works fine, but f7 throws this

Exception has occurred: attempt to index a nil value (local 'str')
stack traceback:
	...ifeBoatAPI/Tools/LifeBoatAPI/Tools/Utils/StringUtils.lua:52: in field 'escape'
	...tAPI/Tools/LifeBoatAPI/Tools/Build/RedundancyRemover.lua:66: in method '_init_from_captures'
	...tAPI/Tools/LifeBoatAPI/Tools/Build/RedundancyRemover.lua:38: in method 'new'
	...tAPI/Tools/LifeBoatAPI/Tools/Build/RedundancyRemover.lua:126: in local 'callable'
	...LifeBoatAPI/Tools/LifeBoatAPI/Tools/Utils/TableUtils.lua:233: in field 'iselect'
	...tAPI/Tools/LifeBoatAPI/Tools/Build/RedundancyRemover.lua:126: in method 'attemptDeletionPass'
	...tAPI/Tools/LifeBoatAPI/Tools/Build/RedundancyRemover.lua:114: in method 'removeRedundantCode'
	.../LifeBoatAPI/Tools/LifeBoatAPI/Tools/Build/Minimizer.lua:94: in method 'minimize'
	...ts/LifeBoatAPI/Tools/LifeBoatAPI/Tools/Build/Builder.lua:64: in method '_buildScript'
	...ts/LifeBoatAPI/Tools/LifeBoatAPI/Tools/Build/Builder.lua:40: in method 'buildMicrocontroller'
	_build/_build.lua:36: in main chunk
	[C]: in ?

**Comment by Krolon0697** [comment]
if I can help in any way by submitting something more - contact me on discord, I don't really use github _at all_

**Comment by nameouschangey** [comment]
Thanks Krolon,

Can you zip up your project and send me it?
It's very possible I broke something.

**Comment by Krolon0697** [comment]
[temporary.zip](https://github.com/nameouschangey/STORMWORKS_VSCodeExtension/files/8840413/temporary.zip)

**Comment by Krolon0697** [comment]
heyyy update it's an issue inside of my custom library, if I don't require it then there's no error
I've tried commenting out most of the things but... it still persists and I can't find the part that makes it go wrong
is there any cap to the size maybe? it's 1000 lines and 36 thousand characters together with the comments and api definitions

**Comment by nameouschangey** [comment]
could you upload the Krolony library project too?
I'm not sure what you could have done to cause that error to be honest - it definitely looks like a bug on my side.

**Comment by Krolon0697** [comment]
sure, but just gonna say that currently I'm preparing to go out so for quite some time I won't be able to confirm that there's nothing wrong in my library, and there very well might be _something_ due to a lot of copy-pasting and conversions
[Krolony.zip](https://github.com/nameouschangey/STORMWORKS_VSCodeExtension/files/8844638/Krolony.zip)
