### ISSUE TITLE
Suggestion: Add option to disable panning from lua

### ISSUE THREAD

**Issue by HendrikPrins** [nameouschangey/STORMWORKS_VSCodeExtension#91]
Currently you have to uncheck Enable Pan in the simulator window every time you want to test panning inside the simulated screen. It would be useful if we could automate this via _simulator_config.lua, similar to what we already have for the screen type (`simulator:setScreen(1, "3x2")`). I suggest something like:
`simulator:enablePan(false)` or `simulator:disablePanning()`

**Comment by nameouschangey** [comment]
Thanks for the suggestion.

Would it be easier if I added the Enable Pan to persistent settings? So without even writing it in code - it'll just keep whatever setting you had thr last time it ran? (which might also be quicker for me to stick in)

**Comment by HendrikPrins** [comment]
Yes that would also work!

**Comment by nameouschangey** [comment]
Added it as a property, will push new release later today.
