### ISSUE TITLE
F7 Compile errors.

### ISSUE THREAD

**Issue by Gibgib52** [nameouschangey/STORMWORKS_VSCodeExtension#93]
Pressing F7 I get this in the output of vscode

```
Compile: 2 error(s)
C:\Program Files\dotnet\sdk\6.0.201\Microsoft.Common.CurrentVersion.targets(3022,7): error MSB4057:  The target "CreateManifestResourceNames" does not exist in the project. 
C:\Program Files\dotnet\sdk\6.0.201\Microsoft.Common.CurrentVersion.targets(3022,7): error MSB4057:  The target "CreateManifestResourceNames" does not exist in the project.
```
attached is a zip with my project and the `Microsoft.Common.CurrentVersion.targets` file.

Sorry if this is not enough information, I will be able to reply or add more info ~12 hours from now.

[f7Bug.zip](https://github.com/nameouschangey/STORMWORKS_VSCodeExtension/files/8875696/f7Bug.zip)

**Comment by nameouschangey** [comment]
mm, I'm not sure why you're getting that at all to be honest, it shouldn't be attempting to "compile" anything.
Could it be that you've got another extension also using the F7 shortcut?

If so, the command to build (CTRL + SHIFT + P) is "Stormworks: Build Project", and you can rebind it to another key.

(Even if you don't have another extension conflicting that you can see, do just try running build via that command and see what happens)

**Comment by Gibgib52** [comment]
ah, something else was using F7, works perfect now. thanks!

**Comment by nameouschangey** [comment]
Awesome, glad it's working for you now :)
