### ISSUE TITLE
Simulator: Map should not actually draw as a background

### ISSUE THREAD

**Issue by nameouschangey** [nameouschangey/Stormworks_VSCodeExtension#94]
Needs testing in-game.

According to people on Discord, the map should draw over everything else on screen - at the point it's drawn. 
It shouldn't simply be in the background.

**Comment by Gibgib52** [comment]
This code reproduces the bug.
```lua
ticks = 0
function onTick()
    gps_x = input.getNumber(1)
    gps_y = input.getNumber(2)
end

function onDraw()
    w = screen.getWidth()
    h = screen.getHeight()
    cw = w/2
    ch = h/2

    -- red circle, half opacity
    screen.setColor(255, 0, 0, 128)
    screen.drawCircleF(cw, ch, 20)

    -- map
    screen.drawMap(gps_x, gps_y, 2)
end
```
both use a 3x3 monitor

Simulator output:
![image](https://user-images.githubusercontent.com/89713712/173146624-474ce3da-9aba-4883-bc48-422025780ff1.png)


Ingame output:
![image](https://user-images.githubusercontent.com/89713712/173146308-3522bab3-63d2-4f46-8869-25f6d0954fb4.png)

**Comment by nameouschangey** [comment]
Changed this behaviour now, fixed.
