### ISSUE TITLE
suggestion tutorial

### ISSUE THREAD

**Issue by samohtGTO** [nameouschangey/STORMWORKS_VSCodeExtension#96]
pls make a tutorial for code library and how to get a pre/post folder i got a hard time trying to understand it

**Comment by nameouschangey** [comment]
It's unclear what exactly you're asking for.
I've said previously, you need to be far more specific when you're requesting things/reporting bugs.

**Comment by samohtGTO** [comment]
i need more info on how to make a library as said in the readme.md becuese idk how to make a lib for code functions
